{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f5ec17be",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-08-17 15:38:11.752 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:12.858 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\env\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-08-17 15:38:12.858 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:12.860 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:12.862 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.372 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.375 Session state does not function when running a script without `streamlit run`\n",
      "2026-08-17 15:38:13.375 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.375 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.392 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.392 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.396 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.399 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.421 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.432 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.467 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.473 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.474 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.475 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.475 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-17 15:38:13.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import streamlit as st\n",
    "from dotenv import load_dotenv\n",
    "from google import genai\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Load API key\n",
    "# --------------------------------------------------\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "API_KEY = os.getenv(\"GEMINI_API_KEY\")\n",
    "\n",
    "if not API_KEY:\n",
    "    st.error(\"GEMINI_API_KEY not found in .env file.\")\n",
    "    st.stop()\n",
    "\n",
    "client = genai.Client(api_key=API_KEY)\n",
    "\n",
    "MODEL_NAME = \"gemini-3.1-flash-lite\"\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Page configuration\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Gemini Local Chat\",\n",
    "    page_icon=\"✨\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Custom CSS\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <style>\n",
    "\n",
    "    .stApp {\n",
    "        background:\n",
    "            radial-gradient(\n",
    "                circle at top left,\n",
    "                rgba(70, 90, 180, 0.16),\n",
    "                transparent 30%\n",
    "            ),\n",
    "            radial-gradient(\n",
    "                circle at bottom right,\n",
    "                rgba(150, 80, 180, 0.12),\n",
    "                transparent 30%\n",
    "            );\n",
    "    }\n",
    "\n",
    "    .main .block-container {\n",
    "        max-width: 950px;\n",
    "        padding-top: 2rem;\n",
    "        padding-bottom: 6rem;\n",
    "    }\n",
    "\n",
    "    .title-container {\n",
    "        text-align: center;\n",
    "        margin-bottom: 2rem;\n",
    "    }\n",
    "\n",
    "    .main-title {\n",
    "        font-size: 2.8rem;\n",
    "        font-weight: 700;\n",
    "        margin-bottom: 0.2rem;\n",
    "    }\n",
    "\n",
    "    .subtitle {\n",
    "        opacity: 0.7;\n",
    "        font-size: 1rem;\n",
    "    }\n",
    "\n",
    "    [data-testid=\"stChatMessage\"] {\n",
    "        border-radius: 18px;\n",
    "        padding: 12px 16px;\n",
    "        margin-bottom: 10px;\n",
    "        border: 1px solid rgba(128,128,128,0.15);\n",
    "    }\n",
    "\n",
    "    [data-testid=\"stChatInput\"] {\n",
    "        border-radius: 20px;\n",
    "    }\n",
    "\n",
    "    .status-box {\n",
    "        padding: 10px 14px;\n",
    "        border-radius: 12px;\n",
    "        border: 1px solid rgba(128,128,128,0.2);\n",
    "        margin-bottom: 15px;\n",
    "    }\n",
    "\n",
    "    </style>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Session state\n",
    "# --------------------------------------------------\n",
    "\n",
    "if \"messages\" not in st.session_state:\n",
    "    st.session_state.messages = []\n",
    "\n",
    "if \"temperature\" not in st.session_state:\n",
    "    st.session_state.temperature = 0.7\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Sidebar\n",
    "# --------------------------------------------------\n",
    "\n",
    "with st.sidebar:\n",
    "\n",
    "    st.title(\"✨ Gemini Chat\")\n",
    "\n",
    "    st.caption(\"Local Streamlit interface\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    st.subheader(\"Model\")\n",
    "\n",
    "    st.code(MODEL_NAME)\n",
    "\n",
    "    st.session_state.temperature = st.slider(\n",
    "        \"Creativity\",\n",
    "        min_value=0.0,\n",
    "        max_value=1.0,\n",
    "        value=0.7,\n",
    "        step=0.1\n",
    "    )\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    st.subheader(\"Conversation\")\n",
    "\n",
    "    if st.button(\n",
    "        \"🗑️ Clear chat\",\n",
    "        use_container_width=True\n",
    "    ):\n",
    "        st.session_state.messages = []\n",
    "        st.rerun()\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    st.caption(\n",
    "        f\"Messages: {len(st.session_state.messages)}\"\n",
    "    )\n",
    "\n",
    "    st.success(\"Gemini API connected\")\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Header\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <div class=\"title-container\">\n",
    "        <div class=\"main-title\">\n",
    "            ✨ Gemini Local\n",
    "        </div>\n",
    "\n",
    "        <div class=\"subtitle\">\n",
    "            Ask anything. Powered by Gemini API.\n",
    "        </div>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Welcome screen\n",
    "# --------------------------------------------------\n",
    "\n",
    "if len(st.session_state.messages) == 0:\n",
    "\n",
    "    st.markdown(\"### 👋 How can I help you today?\")\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    with col1:\n",
    "\n",
    "        if st.button(\n",
    "            \"💻 Explain Transformer architecture\",\n",
    "            use_container_width=True\n",
    "        ):\n",
    "            st.session_state.pending_prompt = (\n",
    "                \"Explain Transformer architecture \"\n",
    "                \"in a simple and understandable way.\"\n",
    "            )\n",
    "\n",
    "        if st.button(\n",
    "            \"📊 Explain RAG\",\n",
    "            use_container_width=True\n",
    "        ):\n",
    "            st.session_state.pending_prompt = (\n",
    "                \"Explain Retrieval Augmented Generation \"\n",
    "                \"with a simple example.\"\n",
    "            )\n",
    "\n",
    "    with col2:\n",
    "\n",
    "        if st.button(\n",
    "            \"🧠 Explain LLM training\",\n",
    "            use_container_width=True\n",
    "        ):\n",
    "            st.session_state.pending_prompt = (\n",
    "                \"Explain how modern LLMs are trained.\"\n",
    "            )\n",
    "\n",
    "        if st.button(\n",
    "            \"🐍 Generate Python code\",\n",
    "            use_container_width=True\n",
    "        ):\n",
    "            st.session_state.pending_prompt = (\n",
    "                \"Give me a useful beginner Python project.\"\n",
    "            )\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Display chat history\n",
    "# --------------------------------------------------\n",
    "\n",
    "for message in st.session_state.messages:\n",
    "\n",
    "    with st.chat_message(message[\"role\"]):\n",
    "\n",
    "        st.markdown(message[\"content\"])\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Chat input\n",
    "# --------------------------------------------------\n",
    "\n",
    "user_prompt = st.chat_input(\n",
    "    \"Ask Gemini anything...\"\n",
    ")\n",
    "\n",
    "\n",
    "# Handle suggestion buttons\n",
    "if \"pending_prompt\" in st.session_state:\n",
    "\n",
    "    user_prompt = st.session_state.pending_prompt\n",
    "\n",
    "    del st.session_state.pending_prompt\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Generate response\n",
    "# --------------------------------------------------\n",
    "\n",
    "if user_prompt:\n",
    "\n",
    "    # Save user message\n",
    "    st.session_state.messages.append(\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": user_prompt\n",
    "        }\n",
    "    )\n",
    "\n",
    "    # Show user message\n",
    "    with st.chat_message(\"user\"):\n",
    "\n",
    "        st.markdown(user_prompt)\n",
    "\n",
    "\n",
    "    # Build conversation history\n",
    "    conversation = []\n",
    "\n",
    "    for msg in st.session_state.messages:\n",
    "\n",
    "        role = (\n",
    "            \"user\"\n",
    "            if msg[\"role\"] == \"user\"\n",
    "            else \"model\"\n",
    "        )\n",
    "\n",
    "        conversation.append(\n",
    "            {\n",
    "                \"role\": role,\n",
    "                \"parts\": [\n",
    "                    {\n",
    "                        \"text\": msg[\"content\"]\n",
    "                    }\n",
    "                ]\n",
    "            }\n",
    "        )\n",
    "\n",
    "\n",
    "    # Assistant response\n",
    "    with st.chat_message(\"assistant\"):\n",
    "\n",
    "        response_placeholder = st.empty()\n",
    "\n",
    "        full_response = \"\"\n",
    "\n",
    "        try:\n",
    "\n",
    "            stream = client.models.generate_content_stream(\n",
    "                model=MODEL_NAME,\n",
    "                contents=conversation\n",
    "            )\n",
    "\n",
    "            for chunk in stream:\n",
    "\n",
    "                if chunk.text:\n",
    "\n",
    "                    full_response += chunk.text\n",
    "\n",
    "                    response_placeholder.markdown(\n",
    "                        full_response + \"▌\"\n",
    "                    )\n",
    "\n",
    "            response_placeholder.markdown(\n",
    "                full_response\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "\n",
    "            full_response = (\n",
    "                f\"Error communicating with Gemini:\\n\\n{e}\"\n",
    "            )\n",
    "\n",
    "            response_placeholder.error(\n",
    "                full_response\n",
    "            )\n",
    "\n",
    "\n",
    "    # Save Gemini response\n",
    "    st.session_state.messages.append(\n",
    "        {\n",
    "            \"role\": \"assistant\",\n",
    "            \"content\": full_response\n",
    "        }\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78bd48de",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env (3.11.15.final.0)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
